version: '3.8'

services:
  postgres:
    container_name: mycontainer
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    image: 'postgres:alpine'
